# Generated by Django 3.0.5 on 2020-04-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255, verbose_name='banner链接')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('versation', models.CharField(max_length=255, verbose_name='版本号')),
                ('time', models.DateField(verbose_name='时间')),
                ('description', models.CharField(max_length=255, verbose_name='详情')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLib',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(verbose_name='题目')),
                ('answer', models.CharField(max_length=255, verbose_name='答案')),
                ('a', models.TextField(verbose_name='选项A')),
                ('b', models.TextField(verbose_name='选项B')),
                ('c', models.TextField(verbose_name='选项C')),
                ('d', models.TextField(verbose_name='选项D')),
            ],
        ),
    ]
