# Generated by Django 3.0.5 on 2020-04-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionLib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlib',
            name='c',
            field=models.TextField(null=True, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='questionlib',
            name='d',
            field=models.TextField(null=True, verbose_name='选项D'),
        ),
    ]
