# Generated by Django 3.0.5 on 2020-04-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionLib', '0002_auto_20200417_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='description',
            field=models.TextField(max_length=255, verbose_name='详情'),
        ),
    ]
