# Generated by Django 3.0.5 on 2020-04-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionLib', '0003_auto_20200417_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(default='image', max_length=255, verbose_name='类型'),
        ),
    ]
