# Generated by Django 3.0.5 on 2020-04-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionLib', '0004_banner_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlib',
            old_name='a',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='questionlib',
            old_name='b',
            new_name='B',
        ),
        migrations.RenameField(
            model_name='questionlib',
            old_name='c',
            new_name='C',
        ),
        migrations.RenameField(
            model_name='questionlib',
            old_name='d',
            new_name='D',
        ),
    ]
